# Uses PyPA's build tool to build a wheel and sdist.
# See https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#packaging-your-project

name: Build packages for distribution
on:
  workflow_call:


jobs:
  packaging:
    runs-on: ubuntu-latest
    name: Packaging
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install tools
        run: python -m pip install build twine

      - name: Build wheel and sdist
        run: python -m build

      # This checks that the "long description" fields renders correctly on PyPI.
      # We don't upload to PyPI, but the two steps below only upload artifacts to GitHub.
      - name: Run twine check
        run: python -m twine check dist/*

      - uses: actions/upload-artifact@v2
        with:
          name: Wheel
          path: dist/*.whl

      - uses: actions/upload-artifact@v2
        with:
          name: Sdist
          path: dist/*.tar.gz
