name: Linting
on:
  workflow_call:
    inputs:
      typechecking-extras:
        description: >
          Space-separated list of package extras to install when type checking.
          (I.e. the entries in `pyproject.toml`'s `[tool.poetry.extras]` section.)
          Defaults to no extras.
        # In the future I'd like to change setup-python-poetry to install all extras
        # by default, using e.g. an implementation of
        # https://github.com/python-poetry/poetry/issues/3413
        type: string
        required: false
        default: ""
      rust-version:
        description: Rust version to install.
        required: false
        default: ""


jobs:
  style:
    runs-on: ubuntu-latest

    name: Style checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        if: "${{ rust-version != '' }}"
        # There don't seem to be versioned releases of this action per se: for each rust
        # version there is a branch which gets constantly rebased on top of master.
        # We pin to a specific commit for paranoia's sake.
        uses: dtolnay/rust-toolchain@fc3253060d0c959bea12a59f10f8391454a0b02d
        with:
          toolchain: ${{ inputs.rust-version }}
      - uses: Swatinem/rust-cache@v2
        if: "${{ rust-version != '' }}"

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1

      - name: Import order (isort)
        run: poetry run isort --check --diff .

      - name: Code style (black)
        run: poetry run black --check --diff .

      - name: Semantic checks (flake8)
        run: poetry run flake8

  mypy:
    runs-on: ubuntu-latest
    name: Typechecking
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        if: "${{ rust-version != '' }}"
        # There don't seem to be versioned releases of this action per se: for each rust
        # version there is a branch which gets constantly rebased on top of master.
        # We pin to a specific commit for paranoia's sake.
        uses: dtolnay/rust-toolchain@fc3253060d0c959bea12a59f10f8391454a0b02d
        with:
          toolchain: ${{ inputs.rust-version }}
      - uses: Swatinem/rust-cache@v2
        if: "${{ rust-version != '' }}"

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1
        with:
          # We want to make use of type hints in optional dependencies too.
          extras: "${{ inputs.typechecking-extras }}"

      - name: Restore/persist mypy's cache
        uses: AustinScola/mypy-cache-github-action@df56268388422ee282636ee2c7a9cc55ec644a41

      - name: Run mypy
        run: poetry run mypy
