name: Linting
on:
  workflow_call:
    inputs:
      typechecking-extras:
        description: >
          Space-separated list of package extras to install when type checking.
          (I.e. the entries in `pyproject.toml`'s `[tool.poetry.extras]` section.)
          Defaults to no extras.
        # In the future I'd like to change setup-python-poetry to install all extras
        # by default, using e.g. an implementation of
        # https://github.com/python-poetry/poetry/issues/3413
        type: string
        required: false
        default: ""


jobs:
  style:
    runs-on: ubuntu-latest

    name: Style checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1
        with:
          install-project: "false"

      - name: Import order (isort)
        run: poetry run isort --check --diff .

      - name: Code style (black)
        run: poetry run black --check --diff .

      - name: Semantic checks (ruff)
        # --quiet suppresses the update check.
        # --format github turns ruff's diagnostics into annotations, so they show up
        # nicely on diffs in Github's web UI
        run: poetry run ruff --quiet --format github .

  mypy:
    runs-on: ubuntu-latest
    name: Typechecking
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1
        with:
          # We want to make use of type hints in optional dependencies too.
          extras: "${{ inputs.typechecking-extras }}"
          install-project: "false"

      - name: Restore/persist mypy's cache
        uses: AustinScola/mypy-cache-github-action@df56268388422ee282636ee2c7a9cc55ec644a41

      - name: Run mypy
        run: poetry run mypy
