name: Linting
on:
  workflow_call:


jobs:
  style:
    runs-on: ubuntu-latest

    name: Style checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1

      - name: Import order (isort)
        run: poetry run isort --check --diff .

      - name: Code style (black)
        run: poetry run black --check --diff .

      - name: Semantic checks (flake8)
        run: poetry run flake8

  mypy:
    runs-on: ubuntu-latest
    name: Typechecking
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Poetry
        uses: matrix-org/setup-python-poetry@v1

      - name: Restore/persist mypy's cache
        uses: AustinScola/mypy-cache-github-action@df56268388422ee282636ee2c7a9cc55ec644a41

      - name: Run mypy
        run: poetry run mypy
