# See also https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ 

name: "Build and upload to PyPI"
on:
  workflow_call:
    inputs:
      repository:
        description: "The package repository to upload to. Defaults to 'testpypi'; use 'pypi' for the regular package index."
        type: string
        required: false
        default: "testpypi"
    secrets:
      PYPI_API_TOKEN:
        required: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"

      - name: "Install packaging tools"
        run: "python -m pip install build twine"

      - name: "Build dist package"
        run: "python -m build"

      - name: "Upload to PyPI"
        run: "python -m twine upload dist/* --verbose"
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: "${{ secrets.PYPI_API_TOKEN }}"
          TWINE_REPOSITORY: "${{ inputs.repository }}"
