name: Move new issues into the issue triage board

on:
  workflow_call:
    inputs:
      project_id:
        description: 'The projectId to add the issue to.'
        required: true
        type: string
      content_id:
        description: 'The node_id of the issue to add.'
        required: true
        type: string
    secrets:
      github_access_token:
        description: 'The bot token for authenticating the request'
        required: true

jobs:
  add_new_issues:
    name: Add new issues to the triage board
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        with:
          headers: '{"GraphQL-Features": "projects_next_graphql"}'
          token: ${{ secrets.github_access_token }}
          query: |
              mutation add_to_project($projectid:ID!,$contentid:ID!) {
                addProjectV2ItemById(input: {projectId: $projectid contentId: $contentid}) {
                item {
                  id
                  }
                }
              }
          projectid: ${{ inputs.project_id }}
          contentid: ${{ inputs.content_id }}
